version: "3.7"

services:
  jenkins:
          #    image: jenkins_w_ansible:python3.6
    image: jenkins_w_ansible:v1
          #image: jenkins
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - ./data:/var/jenkins_home
      - ./artifacts:/var/jenkins_artifacts
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./ansible:/etc/ansible
      - /etc/timezone:/etc/timezone:ro  
      - /etc/localtime:/etc/localtime:ro 
    ports:
      - 8081:8080
      - 50000:50000
    extra_hosts:
      - "gitlab.lbs.local:10.12.6.34"
        #    network_mode: "host"
